---
# Console logger
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services-commons:counters:log:default:1.0"
  level: "trace"

# # Elastic search logger vesion 1.0
# - descriptor: "pip-services:logger:elasticsearch:default:1.0"
#   connection:
#     uri: {{ELASTIC_SEARCH_SERVICE_URI}}{{^ELASTIC_SEARCH_SERVICE_URI}}http://localhost:9200{{/ELASTIC_SEARCH_SERVICE_URI}}

{{#if MONGO_ENABLED}}
# MongoDB Persistence
- descriptor: "trainings-beacons:persistence:mongodb:default:1.0"
  collection: {{MONGO_COLLECTION}}{{^MONGO_COLLECTION}}beacons{{/MONGO_COLLECTION}}
  connection:
    uri: {{MONGO_SERVICE_URI}}
    host: {{MONGO_SERVICE_HOST}}{{^MONGO_SERVICE_HOST}}localhost{{/MONGO_SERVICE_HOST}}
    port: {{MONGO_SERVICE_PORT}}{{^MONGO_SERVICE_PORT}}27017{{/MONGO_SERVICE_PORT}}
    database: {{MONGO_DB}}{{^MONGO_DB}}app{{/MONGO_DB}}
  credential:
    username: {{MONGO_USER}}
    password: {{MONGO_PASS}}
{{/if}}

{{^MOCK_ENABLED}}{{^MONGO_ENABLED}}
# Default in-memory persistence
- descriptor: "trainings-beacons:persistence:memory:default:1.0"
{{/MONGO_ENABLED}}{{/MOCK_ENABLED}}

# Default controller
- descriptor: "trainings-beacons:controller:default:default:1.0"

# HTTP service version 1.0
- descriptor: "trainings-beacons:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# HTTP endpoint version 1.0
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
